# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('date_time', models.DateTimeField()),
                ('region', models.CharField(blank=True, default='', max_length=30)),
                ('content', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
    ]
