# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160606_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300, unique=True),
        ),
    ]
